### ISSUE TITLE
How to initialize properly?

### ISSUE THREAD

**Issue by hemangshah** [fahidattique55/FAPanels#15]
<img width="1051" alt="screen shot 2017-10-04 at 11 30 05 am" src="https://user-images.githubusercontent.com/3313412/31161832-7d9a3862-a8f7-11e7-9f05-6ba26ab139e9.png">

In example code, I can see this

    let rootController = FAPanelController()

But for me, this isn't working.

**Comment by hemangshah** [comment]
@fahidattique55, ̛thanks for coming up! I would like to suggest you reread my problem, as it's totally different then you're thinking. This is the only line I have written and my Xcode is crying with the above error. If you need any more inputs from my side please do let me know.

**Comment by fahidattique55** [comment]
Hi hemangshah,

Can you please confirm me one thing?

Are you not assigning this rootController to window's root controller ? As you said you are using this line only ?

**Comment by fahidattique55** [comment]
@hemangshah.

I think there may be problem with this because I am adding a KVO for FAPanels and If you are not setting the panelController as your window's root controller then this may cause issues as the observer is still observing and not removed.

Thats a great issue by the way. Thanks for using FAPanels and I will for sure deep dive into it. Once issue will get resolve I will let you know.

But for your time safety, Its working when you assign the panel controller to your window's root controller.

Please let me know in case you face issues with that.

Thanks & Regards

**Comment by hemangshah** [comment]
<img width="1030" alt="screen shot 2017-10-04 at 12 19 00 pm" src="https://user-images.githubusercontent.com/3313412/31163080-4d6ab6e2-a8fe-11e7-9aed-8ba8d4a664ae.png">

**Comment by hemangshah** [comment]
@fahidattique55, thanks, I will check with your solution and please update me whenever you fixed this!

**Comment by hemangshah** [comment]
@fahidattique55, I just tried this, and still, the issue is there.
<img width="1033" alt="screen shot 2017-10-04 at 12 21 19 pm" src="https://user-images.githubusercontent.com/3313412/31163136-8ef8c4c8-a8fe-11e7-93ce-767d53b93704.png">

**Comment by fahidattique55** [comment]
@hemangshah,

Can you please verify the pod version? Which one are you running right now?

**Comment by hemangshah** [comment]
@fahidattique55, I am using 

    FAPanels (0.3.1)

**Comment by fahidattique55** [comment]
@hemangshah,

Please make sure you are running pod version 0.3.2. Because this feature was initially added in this pod version. Other wise I will look into other issues you just specified. I also appreciate your efforts and time for sharing the details with me. I will look into other issues soon.

Thanks

**Comment by hemangshah** [comment]
@fahidattique55, Ok, thanks! Let me try installing 0.3.2

**Comment by hemangshah** [comment]
@fahidattique55, I tried above version and now it's giving me this error:

> Command failed due to signal: Segmentation fault: 11

**Comment by hemangshah** [comment]
While type-checking expression at [somePath/AppDelegate.swift:27:22 - line:27:40] RangeText="FAPanelController()"

**Comment by hemangshah** [comment]
You can replicate this issue by creating a new project in Xcode 9 and installing the same pod which you have suggested.

**Comment by hemangshah** [comment]
@fahidattique55, because I need some immediate support, I have integrated  https://github.com/jonkykong/SideMenu in my project. Thanks! Looking forward to using FAPanels in future.

**Comment by katunch** [comment]
Same issue here: Updated to 0.3.2 as suggested and get the error 
I'm using Xcode 9 with swift 3.2 and deployment target 10.3
```
Command failed due to signal: Segmentation fault: 11
While type-checking expression at [somePath/AppDelegate.swift:27:22 - line:27:40] RangeText="FAPanelController()"
```

I think i have to move to another solution like @hemangshah did. Sorry dude..

**Comment by katunch** [comment]
ok it's working with the storyboard approach but you have to set the module by hand to `FAPanels`

**Comment by fahidattique55** [comment]
@hemangshah,

Creating PanelController with code approach was introduced as people were demanding that. You could have use the storyboard approach and that is only few steps to integrate. But Its fine as you wanted some immediate solution. I'll keeping up the FAPanels up to date and looking forward for you to use it in future.

Thanks :)

**Comment by fahidattique55** [comment]
Hi katunch,

With the storyboard approach, I am not sure about why the module did not automatically update to FAPanels for you. Because It should update automatically. But yeah one may face crashes if the module is their own app target and not FAPanels. Thanks for sharing. I will look into the issues you and others are facing with the code approach.

Thanks & Regards

**Comment by fahidattique55** [comment]
@katunch and @hemangshah ,

The issue "Command failed due to signal: Segmentation fault: 11" has been resolved now. Please update the pod to version 0.3.3 and have a look into it. Thanks to all of you for using FAPanels and making it better. I'll keep updating FAPanels with as many features you guys want.

Thanks & Regards
