### ISSUE TITLE
Unknown Class

### ISSUE THREAD

**Issue by blackphnx** [fahidattique55/FAPanels#4]
I've followed the instructions for install but I keep getting this error. Also, even when I copy the sample project onto a new project. Any idea?

2017-08-03 00:46:19.745949-0500 menu[82818:17871549] Unknown class _TtC4menu17FAPanelController in Interface Builder file.
Could not cast value of type 'UIViewController' (0x1110a33f8) to 'FAPanels.FAPanelController' (0x10e28d4a0).
2017-08-03 00:46:19.981588-0500 menu[82818:17871549] Could not cast value of type 'UIViewController' (0x1110a33f8) to 'FAPanels.FAPanelController' (0x10e28d4a0).
(lldb)

**Comment by fahidattique55** [comment]
Hello blackphnx,

You are getting this error because in Interface builder file (i.e storyboard/xib) the controller is not inheriting from the target. Please see the solution to resolve it in below images.

![error_screen_shot](https://user-images.githubusercontent.com/12518061/28966322-e9f91756-792e-11e7-87c4-9827a11e93ed.png)

![error_screen_shot_withannoration](https://user-images.githubusercontent.com/12518061/28966320-e7c11600-792e-11e7-860a-831e81736332.png)

![solution_screen_shot](https://user-images.githubusercontent.com/12518061/28966317-e7656bc0-792e-11e7-9e27-4650f1dd352e.png)

**Comment by fahidattique55** [comment]
I hope this will resolve your issue. Please let me know in case you face any further issues.

Thanks

**Comment by blackphnx** [comment]
Still having the same issue. I am using swift 4 if that makes any difference. 

![screen shot 2017-08-05 at 1 12 24 am](https://user-images.githubusercontent.com/8032366/28993410-54714a6c-797b-11e7-983a-aa7af5f1bb4a.png)
![screen shot 2017-08-05 at 1 11 44 am](https://user-images.githubusercontent.com/8032366/28993409-546f20f2-797b-11e7-837e-add2a442650a.png)

**Comment by voldzi** [comment]
I did exact copy of your demo...and still have the same issue :-(

**Comment by fahidattique55** [comment]
@voldzi Are you using it via code or via storyboard? Also show some code snippets or screenshots so I can help you to diagnose it.

Thanks

**Comment by McExco** [comment]
I solved this problem by uncheck "Inherit from target" box, and specify Module = FAPanels manually.

**Comment by voldzi** [comment]
> I solved this problem by uncheck "Inherit from target" box, and specify Module = FAPanels manually.

Thanks - it helps too!
