### ISSUE TITLE
crash in appdelegate

### ISSUE THREAD

**Issue by MansoorJafari** [fahidattique55/FAPanels#9]
Hi 
after set this code
`let rootController: FAPanelController = window?.rootViewController as! FAPanelController`

app crash and get me this error

Could not cast value of type 'LibraryForDeveloper.ViewController'
my ViewController extend from UIViewController

<img width="322" alt="screen shot 1396-05-20 at 19 44 15" src="https://user-images.githubusercontent.com/15822698/29219561-a7113ea6-7ecd-11e7-99c5-432958e897cf.png">

thanks

**Comment by fahidattique55** [comment]
Hi MansoorJafari,

Did you verify the step 1 that I have mentioned in README.md file. Please verify that your root window is of FAPanels class. Let me know in case the issue still persists.

Thanks & Regards

**Comment by MansoorJafari** [comment]
I create uiviewcontroller without storyboard and with only code.
how to set step 1??

**Comment by fahidattique55** [comment]
Just assign window?.rootViewController = FAPanelController() and then you can set centerVC to panels like,

(window?.rootViewController as! FAPanelController).centerVC =  ViewController()

Thanks & Regards

**Comment by MansoorJafari** [comment]
Thank you for answer to my question, but I can't do this.

**Comment by fahidattique55** [comment]
You are welcome. Why you can not do this? I did not get your point. Can you please explain?

**Comment by MansoorJafari** [comment]
Thanks.
this is my appdelegate
<img width="723" alt="screen shot 1396-05-21 at 14 36 19" src="https://user-images.githubusercontent.com/15822698/29239781-c69ca10e-7f6b-11e7-8705-4a37e36abd23.png">

this is my leftVC
<img width="717" alt="screen shot 1396-05-21 at 14 37 07" src="https://user-images.githubusercontent.com/15822698/29239782-d8facda8-7f6b-11e7-917b-853095f339a2.png">


and this is my mainVC or ViewController
<img width="717" alt="screen shot 1396-05-21 at 14 37 07" src="https://user-images.githubusercontent.com/15822698/29239784-e7ff1e26-7f6b-11e7-8996-444020e44f7d.png">

**Comment by fahidattique55** [comment]
Hi MansoorJafari,

you are setting the root window as UINavigationController which is not FAPanelsController.

Please updated the line,

window?.rootViewController = UINavigationController(rootViewController: centerVC)

to be like this:

let navVC = UINavigationController(rootViewController: centerVC)

window?.rootViewController = FAPanelController()

Now, the window's root controller  is of FAPanelController and now you can access the centerVC property of FAPanelController.

As you want to set your navVC as the centerVC of FApanels so you can do it like,

let rootVC: FAPanelController = window?.rootViewController as! FAPanelController

rootVC.centerVC = navVC


Thanks & Regards

**Comment by MansoorJafari** [comment]
Thank you very much.
problem solve.

**Comment by fahidattique55** [comment]
You are always welcome.

**Comment by CrEaK** [comment]
I tried your example but Xcode throws:
"Missing argument for parameter 'coder' in call"
Example:
"let panelController = FAPanelController()"

It seams that the only init-Method is with NSCoder?

Any idea?
Thanks for your help!

**Comment by fahidattique55** [comment]
Hi CrEaK,

Yes, right now It does not support FAPanelController(). I will add this feature soon.

Thanks & Regards

**Comment by fahidattique55** [comment]
Hi CrEaK,

The feature is added. Please have a look into it. Let me know in case you found any issues or you have any queries.

Thanks & Regards

**Comment by CrEaK** [comment]
Thanks for the fast implementation, but now im getting weird xcode errors :D 
![image](https://user-images.githubusercontent.com/513850/31120393-91f9d0ce-a834-11e7-94a3-88cf54bf3eca.png)

and when xcode compiles I am getting:
`Command failed due to signal: Segmentation fault: 11`

Everything compiles when I am removing the following part:
`let panelController = FAPanelController()`

**Comment by hemangshah** [comment]
@CrEaK , can you please check this [issue](https://github.com/fahidattique55/FAPanels/issues/15)?

**Comment by fahidattique55** [comment]
Hi CrEaK,

Welcome and Thanks for testing it. The issue here is, you are assigning a panelController as window's root controller but the panelController must have at least centerVC assigned in it.

please use this code,

let rootController = FAPanelController()

1. let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
2. let centerVC: CenterVC = mainStoryboard.instantiateViewController(withIdentifier: "CenterVC1") as! CenterVC
3. let centerNavVC = UINavigationController(rootViewController: centerVC)

Now you have created a centerVC embed in a NavigationVC, you can assign this to PanelController as,

4.  _ = rootController.center(centerNavVC).left(leftMenuVC).right(rightMenuVC)

Now assign this panel controller to your window's Root controller as,

window?.rootViewController = rootController


Please let me know in case you found any issues with it. 

Thanks & Regards

**Comment by fahidattique55** [comment]
Hi hemangshah,

You are facing this issue for the same reason I just resolved above. If you want to create FApanelController from code then you have to set a center VC prior to setting the panel controller as your window's root controller.

Please feel free to ask any queries and let me know if you face any issues or you have any suggestion for FAPanels.

Thanks & Regards

**Comment by hemangshah** [comment]
@fahidattique55, let's take this discussion to mine issue as I believe, it's totally different than this. Thanks!

**Comment by fahidattique55** [comment]
@hemangshah,

:) Ok.

**Comment by fahidattique55** [comment]
@CrEaK,

I am for now updating the status of issue as open. Please test it and let me know so that I can mark it closed.

Thanks

**Comment by fahidattique55** [comment]
@CrEaK,

The issue "Command failed due to signal: Segmentation fault: 11" has been resolved now. Please update the pod to version 0.3.3 and have a look into it. Thanks to all of you for using FAPanels and making it better. I'll keep updating FAPanels with as many features you guys want.

Thanks & Regards

**Comment by CrEaK** [comment]
Sorry, I didnt find the time yesterday to test your recommendations. Thanks for your fast help! I will try the new version later today :) 

Thank you for your work! :+1:

**Comment by CrEaK** [comment]
Its now working perfectly! Thanks!
